/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-19 06:25:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tourism.model.TravelPackage;

public final class EditPackage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.tourism.model.TravelPackage");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Edit Package</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"card shadow-sm\">\r\n");
      out.write("            <div class=\"card-header bg-dark text-white\">\r\n");
      out.write("                <h2 class=\"mb-0\">Edit Travel Package</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                ");

                    TravelPackage pkg = (TravelPackage) request.getAttribute("package");
                    String error = (String) request.getAttribute("error");
                    if (error != null) {
                
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                        ");
      out.print( error );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");

                    }
                    if (pkg != null) {
                
      out.write("\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editPackage\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( pkg.getId() );
      out.write("\" />\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"name\" class=\"form-label\">Name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value=\"");
      out.print( pkg.getName() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"destination\" class=\"form-label\">Destination</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"destination\" name=\"destination\" value=\"");
      out.print( pkg.getDestination() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"price\" class=\"form-label\">Price</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.01\" class=\"form-control\" id=\"price\" name=\"price\" value=\"");
      out.print( pkg.getPrice() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"description\" class=\"form-label\">Description</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"description\" name=\"description\" value=\"");
      out.print( pkg.getDescription() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"type\" class=\"form-label\">Type</label>\r\n");
      out.write("                        <select class=\"form-select\" id=\"type\" name=\"type\" onchange=\"toggleField(this.value)\">\r\n");
      out.write("                            <option value=\"Adventure\" ");
      out.print( (pkg instanceof com.tourism.model.AdventurePackage ? "selected" : "") );
      out.write(">Adventure</option>\r\n");
      out.write("                            <option value=\"Leisure\" ");
      out.print( (pkg instanceof com.tourism.model.LeisurePackage ? "selected" : "") );
      out.write(">Leisure</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\" id=\"extraField\">\r\n");
      out.write("                        ");

                            String extra = "";
                            String label = "";
                            if (pkg instanceof com.tourism.model.AdventurePackage) {
                                label = "Activity Type";
                                extra = pkg.getExtraDetails().startsWith("Activity Type: ") ? pkg.getExtraDetails().substring("Activity Type: ".length()) : "";
                            } else if (pkg instanceof com.tourism.model.LeisurePackage) {
                                label = "Hotel Type";
                                extra = pkg.getExtraDetails().startsWith("Hotel Type: ") ? pkg.getExtraDetails().substring("Hotel Type: ".length()) : "";
                            }
                        
      out.write("\r\n");
      out.write("                        <label for=\"extra\" class=\"form-label\">");
      out.print( label );
      out.write("</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"extra\" name=\"extra\" value=\"");
      out.print( extra );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-flex justify-content-between mt-4\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-success\">Update Package</button>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/viewPackages\" class=\"btn btn-secondary\">Back to Packages</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                ");

                    } else {
                
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                        No package loaded for editing.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/viewPackages\" class=\"btn btn-secondary\">Back to Packages</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleField(type) {\r\n");
      out.write("            const label = type === 'Adventure' ? 'Activity Type' : 'Hotel Type';\r\n");
      out.write("            document.getElementById('extraField').innerHTML = `\r\n");
      out.write("                <label for=\"extra\" class=\"form-label\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${label}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"extra\" name=\"extra\" required />\r\n");
      out.write("            `;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
